server:
  port: "8080"
clients:
  gemini:
    key: some-key
    model: some-model
  openai:
    key: some-key
    model: some-model
    maxtokens: 100
  signinwithapple:
    appleclientid: 'some-key'
    teamid: 'some-key'
    keyid: 'some-key'
    privatekey: 'some-key'
  superbase:
    url: 'some-key'
    key: 'some-key'
    accounttablename: 'some-key'
    usagetablename: 'some-key'
prompts:
  eventprompts:
    eventcontexttimelinedetailsprompt: "some-prompt"
    eventcontexttimeprompt: "some-prompt"
    eventcontextinputmessageprompt: "some-prompt"
    eventcontextprevtimelineprompt: "some-prompt"
    eventcontextsysteminstructionprompt: "some-prompt"
    eventcontextsystemresponseprompt: "some-prompt"

    searchcontexthistoryprompt: "some-prompt"
    searchcontextsearchtextprompt: "some-prompt"
    searchcontextsysteminstructionprompt: "some-prompt"
    searchcontextsystemresponseprompt: "some-prompt"
ratelimit:
  ratelimit: 10
  windowinsec: 60
jwtsecret:  "some-key"
